### ISSUE TITLE
Steph branch?

### ISSUE THREAD

**Issue by emilioalaca** [PLS120BookTeam/PLS120Book2018#14]
In the last meeting I gathered that Cale had not made any changes and did not need to submit a pull request or a branch to merge. I also though that Jen and Stephanie had pull requests or branches to be merged. I found and merged a Ch13... from Jen, but I did not find anything from Stephanie.

Please, make sure you are working on the PLSBookTeam/PLS120Book2018 repository and submit your work for end of July merging. Once I merge everything everyone can get new branches and work towards the mid Aug deadline to have at least a complete scaffolding for all chapters.

Chin Up and Mark Down!

**Comment by emilioalaca** [comment]
I have merged all branches now. Please, get a clone/branch and work on that. Make sure to look at chapter 12 to get an idea for format, style, blocks, figures etc. Try to make schematics and colorful figures for explanations wherever you can. For now you can just put hand drafted figures scanned with your phone as placeholders. We can get the final figures later, after we discuss their details.

Congratulations to Jennifer who has attained a postdoc!!

Happy for you, Jen, but we will miss you in PLS120!!!

**Comment by Jleebrazeal** [comment]
Thanks Emilio! :)
